name: Check I18n files CompileMessages

on:
  pull_request:
    branches:
      - 'dev'  # 匹配分支名称以 'pr' 开头
    paths:
      - 'apps/i18n/core/**/*.po'
    types:
      - opened
      - synchronize
      - reopened
jobs:
  compile-messages-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 安装系统依赖
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsasl2-dev python3-dev libldap2-dev libssl-dev


      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install

      - name: Run Compile-Messages
        run: python manage.py compilemessages
