name: Translate README
on:
  workflow_dispatch:
    inputs:
      languages:
        description: "Target languages"
        required: false
        default: "zh-hans,zh-hant,ja,pt-br"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Translate
        uses: BaiJiangJie/translate-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.GPT_API_TOKEN }}
          GPT_MODE: 'gpt-4o-mini'
          TARGET_LANGUAGES: ${{ github.event.inputs.languages }}
