name: Translate README
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: "An example input" # 描述输入
        required: false
        default: "default_value" # 默认值
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Auto Translate
        uses: BaiJiangJie/translate-readme@main
        with:
          gpt_token: ${{ secrets.GPT_API_TOKEN }}
          gpt_mode: 'gpt-4o-mini'
          target_languages: 'zh-hans,zh-hant,ja,pt-br'
