name: Translate README
on:
  workflow_dispatch:
    inputs:
      languages:
        description: "Target languages"
        required: false
        default: "zh-hans,zh-hant,ja,pt-br"
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Auto Translate
        uses: BaiJiangJie/translate-readme@main
        with:
          gpt_token: ${{ secrets.GPT_API_TOKEN }}
          gpt_mode: 'gpt-4o-mini'
          target_languages: ${{ github.event.inputs.languages }}
